### ISSUE TITLE
Broken by D41612: librt.so.1 moved from /usr/lib/ to /lib/

### ISSUE THREAD

**Issue by agrajag9** [shkhln/nvshim#11]
https://github.com/shkhln/libc6-shim/blob/d545115c27d19300f2f0ef6ba5c95f02af6648f4/bin/with-glibc-shim#L24

[D41612](https://reviews.freebsd.org/D41612) moved `/usr/lib/librt.so.1` to `/lib/librt.so.1`

Reference https://github.com/freebsd/freebsd-src/commit/f006023b2281e179374b56db196d03911fad3680

Should be a simple fix.

**Comment by shkhln** [comment]
Should be fixed by edac5ebc519e8c5b4748536d1ed75949f660d153.
