### ISSUE TITLE
Issue on 14.0 nvidia-driver 550.54.14

### ISSUE THREAD

**Issue by verm** [shkhln/nvshim#13]
The shim fails to init with:
```
  cu->cuInit(0) failed -> CUDA_ERROR_OPERATING_SYSTEM: OS call failed or operation not supported on this OS
```

I'm not sure what has caused it worked fine and I'm having difficulty tracing the issue.

Happy trace any suggestions?  Thank you.

**Comment by shkhln** [comment]
Does 535 work?

**Comment by verm** [comment]
Sorry for the late response it took me a while to update no it does not and others seem to be having similar issues:

  https://forums.freebsd.org/threads/cuda-no-longer-works-on-blender-or-ffmpeg-with-nv-sglrun.93169/

Not sure what's changed.

**Comment by verm** [comment]
I completely misunderstood what you meant yes I just downgraded to 535.146.02 and it works fine thank you.

**Comment by shkhln** [comment]
Try 4cfecfb1b8705947127c54561acf3cb71b1a6776.

**Comment by verm** [comment]
Sorry for the late response this version works with 550.54.14 on FreeBSD 14.1.

Thank you for the fix!
