### ISSUE TITLE
got error during the process make

### ISSUE THREAD

**Issue by shuryanc** [shkhln/nvshim#2]
Hi Alex,

Do I miss something? I searched google but cannot find a resolution to fix the error.
Installed Ruby and nvidia-driver 440.82.

mkdir -p build/lib32
cc -m32 -shared -fPIC -Wl,-soname,bsd-librt.so.1 -o build/lib32/dummy-librt.so
ld: error: unable to find library -lgcc
ld: error: unable to find library -lgcc
cc: error: linker command failed with exit code 1 (use -v to see invocation)
*** Error code 1

Thanks.

**Comment by shkhln** [comment]
Do you have `/usr/lib32/libgcc.a`?

**Comment by shuryanc** [comment]
I don't have it. GCC8 to GCC10 are installed, but they don't provide it. Or should I install other package?

**Comment by shkhln** [comment]
It comes with the base system. Well, at least it's supposed to.

**Comment by shuryanc** [comment]
Ok, nevermind. Let me investigate more.

**Comment by shkhln** [comment]
Ahem, let's ping @ericbsd here. That's obviously a GhostBSD issue.

**Comment by shuryanc** [comment]
I confirmed GhostBSD doesn't ship with it to /usr/lib32 by default. I then use use "gcc10 --print-libgcc-file" to find the location of libgcc.a, then copy/link to /usr/lib32/ to fix the issue.

Thanks.
