### ISSUE TITLE
Nv-sglrun with obs (Assertion failed: (0), aborts)

### ISSUE THREAD

**Issue by st1905** [shkhln/nvshim#3]
```
info: OBS 26.0.2-113-gffe4c855 (freebsd)
info: ---------------------------------
info: ---------------------------------
info: audio settings reset:
	samples per sec: 48000
	speakers:        2
info: ---------------------------------
info: Initializing OpenGL...
info: Loading up OpenGL on adapter NVIDIA Corporation GeForce GTX 750 Ti/PCIe/SSE2
info: OpenGL loaded successfully, version 3.3.0 NVIDIA 455.38, shading language 3.30 NVIDIA via Cg compiler
shim_fcntl_impl(44, 1033, ...) is not implemented
Assertion failed: (0), function shim_fcntl_impl, file src/libc/fcntl.c, line 124.
```

I wonder if it would be possible to run obs ?

**Comment by shkhln** [comment]
Well, OBS works for me… 1033 corresponds to [F_ADD_SEALS](https://man7.org/linux/man-pages/man2/fcntl.2.html), which is only useful for descriptors returned by `memfd_create`, which we don't support either. So, this shouldn't really be called.

**Comment by st1905** [comment]
I know its kinda stupid thing to do but i removed `UNIMPLEMENTED_ARGS("%d, %d, ...", fd, cmd);` from fcntl.c and now it works.

![nvenc1](https://user-images.githubusercontent.com/4885199/99229480-21137880-27ff-11eb-9f36-114671fb76df.png)
![nvenc2](https://user-images.githubusercontent.com/4885199/99229486-240e6900-27ff-11eb-9e90-40461b450f4c.png)

**Comment by st1905** [comment]
I also see that [F_ADD_SEALS](https://man7.org/linux/man-pages/man2/fcntl.2.html) was added to [Linuxulator ](https://www.leidinger.net/FreeBSD/dox/linux/html/d6/d01/linux__file_8h.html) recently

**Comment by shkhln** [comment]
`memfd_create` was implemented in CURRENT quite a while ago, however since I don't use CURRENT, I'm not going to do anything with it until FreeBSD 13 is actually released.

**Comment by st1905** [comment]
I can now close this issue, thank you.
