### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by zigster64** [shkhln/nvshim#4]
Thanks - kind of surprised this would work, but glad it does.  Great hack, thanks for sharing.

How hard would it be for NVidia to just fix their Makefile and compile those 3 missing vk_XXXXX functions into the FreeBSD binary ?  Maybe its more complicated than that, but I kind of doubt it.  What do you think ?

**Comment by shkhln** [comment]
> How hard would it be for NVidia to just fix their Makefile and compile those 3 missing vk_XXXXX functions into the FreeBSD binary ? Maybe its more complicated than that, but I kind of doubt it. What do you think ?

I can't provide any answers for them. It could be that they need some changes to the build pipeline and/or QA process to properly support Vulkan, or maybe this is just a very low priority task.
